name: Snyk 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

     
      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Test
        run: snyk code test --severity-threshold=high