name: unit-test
on: [push]
jobs:
  test-sureci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Pytest Yukle
        run: pip install pytest
      - name: testleri calistir
        run: pytest